version: '3'

services:

  fastapi-app:
    container_name: cvdeploy
    build: .
    ports:
      - "8001:8001"
    environment:
    - OPENAI_KEY=${OPENAI_KEY}
    - API_SERVER_IP=${API_SERVER_IP}
    networks:
      micro-services-network:
        ipv4_address: 192.168.0.10
    restart: always
  
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ~/redis_data:/data
    networks:
        micro-services-network:
          ipv4_address: 192.168.0.7
  
  worker:
    container_name: celery_workers
    build:
      context: .
      dockerfile: Dockerfile.Celery
    command: celery -A app.services.celery.celery_config.celery_app worker --loglevel=info
    environment:
    - OPENAI_KEY=${OPENAI_KEY}
    depends_on:
      - redis
      - fastapi-app
    networks:
        micro-services-network:
          ipv4_address: 192.168.0.8
    volumes:
      - ~/celery_store1:/celery-data


networks:
  micro-services-network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: "192.168.0.1"