version: '3'

services:

    testing:
      container_name: CI
      build:
        context: .
        dockerfile: Dockerfile.CI
      env_file:
        - ~/.cv_deploy.env
      volumes:
        - ~/model_path/documents:/app/documents
        - ~/model_path/cv_model:/app/cv_model
