name: Deployment

on:
  push:
    branches: ["md-branch"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Deploy using Docker Compose
        run: |
          docker-compose -f _cd_pipeline.yaml up --build -d
        env:
          # Define any additional environment variables needed here
          MODEL_PATH: cv_model/TCM1.pth
