name: Testing

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Test with pytest
      run: |
        docker-compose -f _ci_pipeline.yml up --build -d
